### ISSUE TITLE
用到的csv是哪个

### ISSUE THREAD

**Issue by BrandNewJimZhang** [BanZhan/RF-and-PC#1]
您好！我在复现您的结论（包括图），请问在`network`文件中`proximity-class.a.csv`是哪个呀，在您文章的SI中只有一个xlsx，请问可以上传吗？盼复！

**Comment by BanZhan** [comment]
您好，感谢阅读和复现我的文章。代码中所需数据上传在我的researchgate个人网页了。网址如下：https://www.researchgate.net/profile/Zhan_Ban/publications
如有问题，麻烦您联系我。
班崭

发件人：Jim Zhang <notifications@github.com>
发送日期：2020-07-06 20:09:27
收件人：BanZhan/RF-and-PC <RF-and-PC@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[BanZhan/RF-and-PC] 用到的csv是哪个 (#1)

您好！我在复现您的结论（包括图），请问在network文件中proximity-class.a.csv是哪个呀，在您文章的SI中只有一个xlsx，请问可以上传吗？盼复！

**Comment by BrandNewJimZhang** [comment]
好的好的，看到了，感谢！
